$ time ./thumbnail_generator.py
Traceback (most recent call last):
  File "./thumbnail_generator.py", line 10, in <module>
    import PIL
ModuleNotFoundError: No module named 'PIL'

real    0m2.158s
user    0m0.000s
sys     0m0.000s
